name: Deploy to AWS Amplify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Build application
      run: npm run build
      
    - name: Test build output
      run: |
        if [ ! -d "out" ]; then
          echo "Build output directory not found"
          exit 1
        fi
        echo "Build output size: $(du -sh out)"
        
    # Amplify will automatically deploy when connected to the repository
    # This workflow ensures the build works before Amplify attempts deployment
